name: Deploy VPC
on:
  push:
    branches: [ "main" ]





jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v4

      
      - name: Initialize terraform
        run: echo Hello, world!

      
      - name: Configure workspace
        run:  
           terraform workspace new dev || terraform workspace select dev
      

          
